// Build the v5 DRAFT into its own artifact. Mirrors ../../build.js exactly, except that the
// source and the output are both confined to this proposal directory.
//
// Why a separate builder at all: build.js hardcodes SRC to the repo-root source and writes the
// prod artifact back to the repo root, which is the file recreate-wp-page.js deploys. Running it
// against a draft would stage an unapproved redesign for the next deploy. Nothing here writes
// outside proposals/v5/ except the shared node_modules-driven scratch files in landing-src,
// which are regenerated by any build anyway.
//
// usage: node build_v5.js
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const HERE = __dirname;
const LSRC = path.join(HERE, "..", "..");          // landing-src (for node_modules + npx)
const SRC = path.join(HERE, "run-santa-fe-2026.src.html");
const OUT = path.join(HERE, "run-santa-fe-2026.prod.src.html");
const WORK = path.join(HERE, "work");
fs.mkdirSync(path.join(WORK, "src"), { recursive: true });
fs.mkdirSync(path.join(WORK, "shim"), { recursive: true });

const html = fs.readFileSync(SRC, "utf8");

const styleM = html.match(/<style>([\s\S]*?)<\/style>/);
if (!styleM) throw new Error("style block not found");
const customCss = styleM[1];

const scriptM = html.match(/<script type="text\/babel"[^>]*>([\s\S]*?)<\/script>/);
if (!scriptM) throw new Error("babel script not found");
let body = scriptM[1];
const cut = body.indexOf("const RACE_START");
if (cut < 0) throw new Error("RACE_START marker not found");
body = body.slice(cut);
body = body.replace(
  'ReactDOM.createRoot(document.getElementById("root")).render(<App/>);',
  'createRoot(document.getElementById("root")).render(<App/>);'
);
if (body.includes("ReactDOM")) throw new Error("unexpected ReactDOM reference remains");

const header = `import React, {useState, useEffect, useMemo, useRef} from "react";
import {createRoot} from "react-dom/client";
import {Award, Shirt, Soup, Timer, Camera, Backpack, Mountain, Menu, X, ChevronDown, ChevronRight, Accessibility, Facebook, Instagram, Twitter} from "lucide-react";
const ICONS = {Award, Shirt, Soup, Timer, Camera, Backpack, Mountain, Menu, X, ChevronDown, ChevronRight, Accessibility, Facebook, Instagram, Twitter};
function Ic({name, size = 22, color}) {
  const C = ICONS[name];
  if (C) return <C size={size} strokeWidth={2} color={color || "currentColor"} aria-hidden="true"/>;
  return <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="2" fill="currentColor" stroke="none"/></svg>;
}
`;
fs.writeFileSync(path.join(WORK, "src", "app.jsx"), header + body);
fs.writeFileSync(path.join(WORK, "shim", "react.js"), "module.exports = window.React;\n");
fs.writeFileSync(path.join(WORK, "shim", "react-dom-client.js"),
  "module.exports = { createRoot: (el) => window.ReactDOM.createRoot(el) };\n");

const rel = p => path.relative(LSRC, p).replace(/\\/g, "/");
execSync(`npx esbuild ${rel(path.join(WORK, "src", "app.jsx"))} --bundle --minify --loader:.jsx=jsx ` +
  `--alias:react=./${rel(path.join(WORK, "shim", "react.js"))} ` +
  `--alias:react-dom/client=./${rel(path.join(WORK, "shim", "react-dom-client.js"))} ` +
  `--outfile=${rel(path.join(WORK, "dist-bundle.js"))}`, { cwd: LSRC, stdio: "inherit" });

// The content glob MUST be absolute. Tailwind resolves a relative glob against the CWD, not
// against the config file, and this runs with cwd = landing-src -- so './src/app.jsx' silently
// scanned the CANONICAL build's app.jsx instead of v5's. Every Tailwind class introduced only in
// v5 was therefore dropped from the stylesheet: the wider grid gaps looked applied in the source
// and measured ~10px in the browser. A build that reads the wrong file and still succeeds is
// exactly the two-directory trap this proposal tree exists to avoid.
fs.writeFileSync(path.join(WORK, "tailwind.config.js"),
  "module.exports = { content: [" + JSON.stringify(path.join(WORK, "src", "app.jsx").replace(/\\/g, "/")) +
  "], corePlugins: { preflight: true } };\n");
fs.writeFileSync(path.join(WORK, "tw-input.css"), "@tailwind base;\n@tailwind utilities;\n");
execSync(`npx tailwindcss -c ${rel(path.join(WORK, "tailwind.config.js"))} ` +
  `-i ${rel(path.join(WORK, "tw-input.css"))} ` +
  `-o ${rel(path.join(WORK, "dist-tailwind.css"))} --minify`, { cwd: LSRC, stdio: "inherit" });

const bundle = fs.readFileSync(path.join(WORK, "dist-bundle.js"), "utf8");
const tw = fs.readFileSync(path.join(WORK, "dist-tailwind.css"), "utf8");
fs.writeFileSync(path.join(WORK, "custom.css"), customCss);
execSync(`npx esbuild ${rel(path.join(WORK, "custom.css"))} --minify --outfile=${rel(path.join(WORK, "dist-custom.css"))}`,
  { cwd: LSRC, stdio: "inherit" });
const customMin = fs.readFileSync(path.join(WORK, "dist-custom.css"), "utf8");

const ldA = html.indexOf('<script type="application/ld+json">');
const ldB = html.indexOf('</scr' + 'ipt>', ldA);
const LDJSON = ldA > -1 ? html.slice(ldA, ldB + 9) + "\n" : "";

const out = `<title>Run Santa Fe 2026</title>
${LDJSON}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,400..900&family=Martian+Mono:wght@400;700&display=swap">
<style>${tw}</style>
<style>${customMin}</style>
<div id="root"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.3.1/umd/react.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.3.1/umd/react-dom.production.min.js"></script>
<script>${bundle}</script>
`;
fs.writeFileSync(OUT, out);
console.log("v5 artifact:", Math.round(out.length / 1024) + " KB",
  "| bundle:", Math.round(bundle.length / 1024) + " KB",
  "| tailwind:", Math.round(tw.length / 1024) + " KB");
console.log("wrote", OUT);
